# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'DosmonoDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Dosmono', :path => './cy_Dosmono'
  pod 'Masonry'
  pod 'SVProgressHUD'

  target 'DosmonoDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DosmonoDemoUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            end
        end
    end
end
